; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:waveshare-dial]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitm-1
framework = arduino

board_build.arduino.memory_type = qio_opi 
board_build.partitions = default_16MB.csv
; this is the recommendation from Waveshare, change as you wish
;board_build.partitions = huge_app.csv
board_upload.flash_size = 16MB

lib_deps =
  lvgl@8.4

build_flags = 
  -DBOARD_HAS_PSRAM
  -DLV_CONF_SKIP
  -DLV_CONF_INCLUDE_SIMPLE
  -DLV_COLOR_DEPTH=16
  -DLV_COLOR_16_SWAP=1

; when you're done testing, remove these two lines
  -DLV_USE_DEMO_WIDGETS=1
  -DLV_BUILD_EXAMPLES=1